# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 17:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remote_addr', models.CharField(db_index=True, max_length=255)),
                ('date', models.DateTimeField(blank=True, db_index=True)),
                ('method', models.CharField(max_length=50)),
                ('path', models.TextField(db_index=True)),
                ('status_code', models.IntegerField()),
                ('user_agent', models.TextField(blank=True)),
                ('request_headers', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('response_headers', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('query_strings', django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
                ('parsed_raw_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
